#       _ _        __  __         _             
#  __ _| | |  ___ / _|/ _|  ___  | |_ __ _ __ _ 
# / _` | | | / _ \  _|  _| |___| |  _/ _` / _` |
# \__,_|_|_| \___/_| |_|          \__\__,_\__, |
#                                         |___/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Tag All Off'
description: 'Automation to turn all lights off using NFC Tags next to our bed.'
trigger:
  - platform: tag
    tag_id: 09b945be-22fe-42cd-addb-77e9e40a0a9f
  - platform: tag
    tag_id: 3e0bd108-211c-4220-b379-7b6eac6851be
condition: []
action:
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - bedroom
      - hall
      - kitchen
      - living_room
      - office
mode: single
