#  ___  ___ ___ _  _   _ _  _____    ___ ___  _  _ ___ ___ ___ 
# |   \| __| __/_\| | | | ||_   _|  / __/ _ \| \| | __|_ _/ __|
# | |) | _|| _/ _ \ |_| | |__| |   | (_| (_) | .` | _| | | (_ |
# |___/|___|_/_/ \_\___/|____|_|    \___\___/|_|\_|_| |___\___|
#                                                              
#--FROM https://github.com/smcnab1/op-question-mark
#---Activates the HA Default Config.

default_config: ~
