#  _  _  ___  __  __ ___     _   ___ ___ ___ ___ _____ _   _  _ _____ 
# | || |/ _ \|  \/  | __|   /_\ / __/ __|_ _/ __|_   _/_\ | \| |_   _|
# | __ | (_) | |\/| | _|   / _ \\__ \__ \| |\__ \ | |/ _ \| .` | | |  
# |_||_|\___/|_|  |_|___| /_/ \_\___/___/___|___/ |_/_/ \_\_|\_| |_|  
#                                                                     
#--FROM https://github.com/smcnab1/op-question-mark
#---Activates packaged HA config.

homeassistant:
  # Load packages
  packages: !include_dir_named integrations