#       _                                                  _   _  __                _   _          
#  __ _| |__ _ _ _ _ __    __ _ _ _ _ __    ___   _ _  ___| |_(_)/ _|_  _   __ _ __| |_(_)___ _ _  
# / _` | / _` | '_| '  \  / _` | '_| '  \  |___| | ' \/ _ \  _| |  _| || | / _` / _|  _| / _ \ ' \ 
# \__,_|_\__,_|_| |_|_|_| \__,_|_| |_|_|_|       |_||_\___/\__|_|_|  \_, | \__,_\__|\__|_\___/_||_|
#                                                                    |__/                          
#--FROM https://github.com/smcnab1/op-question-mark

alias: Alarm Arm Notify Actions
description: >-
  This automation then arms the alarm and sends notifications to everyone to
  confirm it is now armed.
mode: single
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: ARM_ALARM
    context:
      user_id:
        - 9ffd5fe9c4c84dd2b9213f04d70b4495
    id: LEAHARM
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: ARM_ALARM
    context:
      user_id:
        - 6728110b2495497fab6d74e5d2ec0861
    id: SAMARM
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: person.sam
        state: not_home
      - condition: state
        entity_id: person.leah
        state: not_home
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: disarmed
action:
  - if:
      - condition: trigger
        id: LEAHARM
    then:
      - service: alarm_control_panel.alarm_arm_away
        data: {}
        target:
          entity_id: alarm_control_panel.home_alarm
      - wait_for_trigger:
          - platform: state
            entity_id:
              - alarm_control_panel.home_alarm
            to: armed_away
        continue_on_timeout: false
      - service: notify.mobile_app_sams_iphone
        data:
          message: Leah has armed the Alarm
          title: ALARM ARMED
      - service: notify.mobile_app_leah_iphone
        data:
          message: You have armed the Alarm.
          title: ALARM ARMED
  - if:
      - condition: trigger
        id: SAMARM
    then:
      - service: alarm_control_panel.alarm_arm_away
        data: {}
        target:
          entity_id: alarm_control_panel.home_alarm
      - wait_for_trigger:
          - platform: state
            entity_id:
              - alarm_control_panel.home_alarm
            to: armed_away
        continue_on_timeout: false
      - service: notify.mobile_app_sams_iphone
        data:
          message: You have armed the Alarm
          title: ALARM ARMED
      - service: notify.mobile_app_leah_iphone
        data:
          message: Sam has armed the Alarm.
          title: ALARM ARMED
