id: '1661173426932'
alias: TV Living Room Camera Notification
description: ''
trigger:
- platform: mqtt
  topic: frigate/events
  payload: living_room
condition:
- condition: and
  conditions:
  - condition: template
    value_template: '{{ trigger.payload_json[''after''][''label''] == ''person''
      }}'
- condition: state
  entity_id: input_boolean.sleeping
  state: 'on'
  for:
    hours: 0
    minutes: 30
    seconds: 0
- type: is_motion
  condition: device
  device_id: 927eeec52f8bad9880e5e24cc2a40e17
  entity_id: binary_sensor.living_room_motion
  domain: binary_sensor
action:
- service: media_player.volume_set
  data:
    volume_level: 0.7
  target:
    entity_id: media_player.bedroom
- service: media_player.turn_on
  data: {}
  target:
    entity_id: media_player.fire_tv_192_168_1_94
- service: media_player.play_media
  target:
    entity_id: media_player.bedroom
  data:
    media_content_id: media-source://media_source/local/Alarm-System_config_www_alarm1
      (1).mp3
    media_content_type: audio/mpeg
  metadata:
    title: Alarm-System_config_www_alarm1 (1).mp3
    thumbnail:
    media_class: music
    children_media_class:
    navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://media_source
- service: tts.cloud_say
  data:
    entity_id: media_player.bedroom
    message: Motion Detected in Living Room. Look at the TV
- service: notify.fire_tv
  data:
    message: Motion Detected in Living Room
    title: MOTION DETECTED IN LIVING ROOM
    data:
      duration: 30
      fontsize: large
      position: center
      color: red
      interrupt: 1
      icon:
        path: /www/warning-icon.png
      image:
        url: http://ccab4aaf-frigate:5000/api/events/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
mode: single
