#       _                  _       _                           _ _      _   _   _           
#  __ _| |__ _ _ _ _ __   | |_ _ _(_)__ _ __ _ ___ _ _   ___  | (_)__ _| |_| |_(_)_ _  __ _ 
# / _` | / _` | '_| '  \  |  _| '_| / _` / _` / -_) '_| |___| | | / _` | ' \  _| | ' \/ _` |
# \__,_|_\__,_|_| |_|_|_|  \__|_| |_\__, \__, \___|_|         |_|_\__, |_||_\__|_|_||_\__, |
#                                   |___/|___/                    |___/               |___/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: Alarm Trigger Lighting
description: Trigger lighting automation when alarm is triggered to flash red
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
    to: triggered
    id: alarm-is-triggered
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
    to: disarmed
    id: alarm-is-disarmed
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: alarm-is-triggered
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: alarm_control_panel.home_alarm
                  state: disarmed
              sequence:
                - service: light.turn_on
                  data:
                    brightness_pct: 100
                    color_name: red
                  target:
                    entity_id:
                      - light.bedroom_leds
                      - light.hall_leds
                      - light.kitchen_leds
                      - light.living_room_leds
                      - light.living_room_tv_leds
                      - light.living_room_display_led
                      - light.office_leds
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
                - service: light.turn_off
                  data: {}
                  target:
                    entity_id:
                      - light.bedroom_leds
                      - light.hall_leds
                      - light.kitchen_leds
                      - light.living_room_leds
                      - light.living_room_tv_leds
                      - light.office_leds
                      - light.living_room_display_led
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
      - conditions:
          - condition: trigger
            id: alarm-is-disarmed
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id:
                - light.bedroom_leds
                - light.hall_leds
                - light.kitchen_leds
                - light.living_room_display_led
                - light.living_room_leds
                - light.living_room_tv_leds
                - light.office_leds
    default: []
mode: restart
