#_                  _       _                                                _ 
#  __ _| |__ _ _ _ _ __   | |_ _ _(_)__ _ __ _ ___ _ _   ___   ___ ___ _  _ _ _  __| |
# / _` | / _` | '_| '  \  |  _| '_| / _` / _` / -_) '_| |___| (_-</ _ \ || | ' \/ _` |
# \__,_|_\__,_|_| |_|_|_|  \__|_| |_\__, \__, \___|_|         /__/\___/\_,_|_||_\__,_|
#                                   |___/|___/                                        
#--FROM https://github.com/smcnab1/op-question-mark

alias: "Alarm Trigger Sound"
description: Trigger siren and TTS when alarm is triggered
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
    to: triggered
    id: alarm-is-triggered
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
    to: disarmed
    id: alarm-is-disarmed
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: alarm-is-triggered
        sequence:
          - service: media_player.turn_on
            data: {}
            target:
              entity_id:
                - media_player.bedroom_google_home
                - media_player.living_room_google_home
          - service: media_player.volume_set
            data:
              volume_level: 1
            target:
              entity_id:
                - media_player.living_room_sonos
                - media_player.bedroom_google_home
                - media_player.living_room_google_home
          - repeat:
              until:
                - condition: state
                  entity_id: alarm_control_panel.home_alarm
                  state: disarmed
              sequence:
                - service: media_player.play_media
                  data:
                    media_content_id: >-
                      http://homeassistant.local:8123/local/Alarm-System_config_www_alarm1.mp3
                    media_content_type: music
                    enqueue: play
                  target:
                    entity_id: media_player.living_room_sonos
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - parallel:
                    - service: tts.cloud_say
                      data:
                        entity_id: media_player.bedroom_google_home
                        message: >-
                          Alarm has been activated. Police have been called and
                          are on the way
                    - service: tts.cloud_say
                      data:
                        entity_id: media_player.living_room_google_home
                        message: >-
                          Alarm has been activated. Police have been called and
                          are on the way
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 30
                    milliseconds: 0
                - parallel:
                    - service: tts.cloud_say
                      data:
                        entity_id: media_player.bedroom_google_home
                        message: Police are now 1 minute away
                    - service: tts.cloud_say
                      data:
                        entity_id: media_player.living_room_google_home
                        message: Police are now 1 minute away
      - conditions:
          - condition: trigger
            id: alarm-is-disarmed
        sequence:
          - service: media_player.media_stop
            data: {}
            target:
              entity_id: media_player.living_room_sonos
          - service: media_player.volume_set
            data:
              volume_level: 0.4
            target:
              entity_id:
                - media_player.living_room_sonos
                - media_player.bedroom_google_home
                - media_player.living_room_google_home
    default: []
mode: restart
