#       _                  _       _                                    _   _  __      
#  __ _| |__ _ _ _ _ __   | |_ _ _(_)__ _ __ _ ___ _ _   ___   _ _  ___| |_(_)/ _|_  _ 
# / _` | / _` | '_| '  \  |  _| '_| / _` / _` / -_) '_| |___| | ' \/ _ \  _| |  _| || |
# \__,_|_\__,_|_| |_|_|_|  \__|_| |_\__, \__, \___|_|         |_||_\___/\__|_|_|  \_, |
#                                   |___/|___/                                    |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: Alarm Trigger Notify
description: >-
  Automation to notify everyone when the alarm is triggered when set to armed
  away and nobody home.
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
    to: triggered
action:
  - service: notify.mobile_app_leah_s_iphone
    data:
      title: INTRUDER ALERT - HOME ALARM TRIGGERED
      message: What would you like to do?
      data:
        presentation_options:
          - alert
        push:
          sound:
            name: 3rd_party_critical.caf
            critical: 1
            volume: 1
          interruption-level: critical
        actions:
          - action: URI
            title: View Cameras
            uri: /ccab4aaf_frigate/dashboard
            icon: sfsymbols:camera.circle.fill
          - action: DISARM_ALARM
            title: Disarm
            icon: sfsymbols:bell.fill
            destructive: true
          - action: CALL
            title: Call Sam
            uri: !secret sam_no
            icon: sfsymbols:phone.fill
          - action: CALL
            title: Call the Police
            uri: tel:999
            icon: sfsymbols:phone.fill
            destructive: true
  - service: notify.mobile_app_iphone
    data:
      title: INTRUDER ALERT - HOME ALARM TRIGGERED
      message: What would you like to do?
      data:
        presentation_options:
          - alert
        push:
          sound:
            name: 3rd_party_critical.caf
            critical: 1
            volume: 1
          interruption-level: critical
        actions:
          - action: URI
            title: View Cameras
            uri: /ccab4aaf_frigate/dashboard
            icon: sfsymbols:camera.circle.fill
          - action: DISARM_ALARM
            title: Disarm
            icon: sfsymbols:bell.fill
            destructive: true
          - action: CALL
            title: Call Leah
            uri: !secret leah_no
            icon: sfsymbols:phone.fill
          - action: CALL
            title: Call the Police
            uri: tel:999
            icon: sfsymbols:phone.fill
            destructive: true
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: notify.mobile_app_leah_s_iphone
    data:
      title: INTRUDER ALERT - HOME ALARM TRIGGERED
      message: What would you like to do?
      data:
        presentation_options:
          - alert
        push:
          sound:
            name: 3rd_party_critical.caf
            critical: 1
            volume: 1
          interruption-level: critical
        actions:
          - action: URI
            title: View Cameras
            uri: /ccab4aaf_frigate/dashboard
            icon: sfsymbols:camera.circle.fill
          - action: DISARM_ALARM
            title: Disarm
            icon: sfsymbols:bell.fill
            destructive: true
          - action: CALL
            title: Call Sam
            uri: !secret sam_no
            icon: sfsymbols:phone.fill
          - action: CALL
            title: Call the Police
            uri: tel:999
            icon: sfsymbols:phone.fill
            destructive: true
  - service: notify.mobile_app_iphone
    data:
      title: INTRUDER ALERT - HOME ALARM TRIGGERED
      message: What would you like to do?
      data:
        presentation_options:
          - alert
        push:
          sound:
            name: 3rd_party_critical.caf
            critical: 1
            volume: 1
          interruption-level: critical
        actions:
          - action: URI
            title: View Cameras
            uri: /ccab4aaf_frigate/dashboard
            icon: sfsymbols:camera.circle.fill
          - action: DISARM_ALARM
            title: Disarm
            icon: sfsymbols:bell.fill
            destructive: true
          - action: CALL
            title: Call Leah
            uri: !secret leah_no
            icon: sfsymbols:phone.fill
          - action: CALL
            title: Call the Police
            uri: tel:999
            icon: sfsymbols:phone.fill
            destructive: true
mode: single
