#  _____ ___    ___   _____ ___          ___ ___    ___ ___  _  _ ___ ___ ___ 
# |_   _| _ \  /_\ \ / /_ _/ __|  ___   / __|_ _|  / __/ _ \| \| | __|_ _/ __|
#   | | |   / / _ \ V / | |\__ \ |___| | (__ | |  | (_| (_) | .` | _| | | (_ |
#   |_| |_|_\/_/ \_\_/ |___|___/        \___|___|  \___\___/|_|\_|_| |___\___|
#                                                                             
#--FROM https://github.com/smcnab1/op-question-mark

language: python
python:
  - "3.7.3"
  - "3.6.4"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config --info all
before_install:
  - mv travis_secrets.yaml secrets.yaml
