#    _  _   _ _____ ___  __  __   _ _____ ___ ___  _  _ ___ 
#   /_\| | | |_   _/ _ \|  \/  | /_\_   _|_ _/ _ \| \| / __|
#  / _ \ |_| | | || (_) | |\/| |/ _ \| |  | | (_) | .` \__ \
# /_/ \_\___/  |_| \___/|_|  |_/_/ \_\_| |___\___/|_|\_|___/
#                                                           
#--FROM https://github.com/smcnab1/op-question-mark
#--Placeholder for Automations. All can be found in automations directory
[]