<<<<<<< HEAD

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
=======
homeassistant:
  # Load packages
  packages: !include_dir_named integrations
>>>>>>> 8e2a71c4e2c3fd8ec67e240b8930b179ad9ee990
