#   ___ ___  _  _ ___ ___ ___ _   _ ___    _ _____ ___ ___  _  _ 
#  / __/ _ \| \| | __|_ _/ __| | | | _ \  /_\_   _|_ _/ _ \| \| |
# | (_| (_) | .` | _| | | (_ | |_| |   / / _ \| |  | | (_) | .` |
#  \___\___/|_|\_|_| |___\___|\___/|_|_\/_/ \_\_| |___\___/|_|\_|
#                                                                
#--FROM https://github.com/smcnab1/op-question-mark

homeassistant:
  # Load packages
  packages: !include_dir_named integrations

lovelace:
  mode: storage
  dashboards:
    lovelace-minimalist-2:
      mode: yaml
      title: Minimalist Phone
      icon: mdi:phone
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/adaptive-dash/adaptive-ui-2.yaml

samsungtv_smart:
  - host: !secret samsung_tv_host
    source_list: '{"TV": "ST_TV", "ST_HDMI1": "DVD", "ST_HDMI2": "LAPTOP", "ST_HDMI3": "UNUSED", "ST_HDMI4": "UNUSED"}'
    app_list: '{"Netflix": "11101200001/org.tizen.netflix-app", "Prime Video": "3201512006785/org.tizen.primevideo", "Spotify": "3201606009684/rJeHak5zRg.Spotify", "YouTube": "111299001912/9Ur5IzDKqV.TizenYouTube", "My5": "EkzyZtmneG.My5", "Paramount+": "rJyOSqC6Up.PPlusIntl", "Disney+": "MCmYXNxgcu.DisneyPlus", "4OD": "OCaxbgg9v6.chfourctv", "ITVHub": "OEvCiupaFR.ITVHub", "BBC iPlayer": "DqEoaplKlw.bbchybrid", "Internet": "org.tizen.browser"}'