id: '1660667422220'
name: 'Scene: Living Room Day'
entities:
  light.living_room_dining_led:
    supported_color_modes:
    - hs
    icon: mdi:led-strip-variant
    friendly_name: 'Living Room: Dining LED'
    supported_features: 0
    color_mode: hs
    brightness: 255
    hs_color:
    - 30
    - 100
    rgb_color:
    - 255
    - 127
    - 0
    xy_color:
    - 0.612
    - 0.374
    state: 'on'
  light.living_room_leds:
    supported_color_modes:
    - hs
    icon: mdi:led-strip-variant
    friendly_name: 'Living Room: LEDs'
    supported_features: 0
    color_mode: hs
    brightness: 252
    hs_color:
    - 30
    - 100
    rgb_color:
    - 255
    - 127
    - 0
    xy_color:
    - 0.612
    - 0.374
    state: 'on'
  light.living_room_tv_leds:
    supported_color_modes:
    - hs
    icon: mdi:led-strip-variant
    friendly_name: 'Living Room: TV LEDs'
    supported_features: 0
    color_mode: hs
    brightness: 252
    hs_color:
    - 30
    - 100
    rgb_color:
    - 255
    - 127
    - 0
    xy_color:
    - 0.612
    - 0.374
    state: 'on'
icon: mdi:weather-sunny
metadata:
  light.living_room_dining_led:
    entity_only: true
  light.living_room_leds:
    entity_only: true
  light.living_room_tv_leds:
    entity_only: true
