#  _ _     _                                           _           
# | (_)_ _(_)_ _  __ _   _ _ ___  ___ _ __    ___   __| |__ _ _  _ 
# | | \ V / | ' \/ _` | | '_/ _ \/ _ \ '  \  |___| / _` / _` | || |
# |_|_|\_/|_|_||_\__, | |_| \___/\___/_|_|_|       \__,_\__,_|\_, |
#                |___/                                        |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Living Room Day'
description: 'Automation to activate living room day time scene.'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.living_room_day
mode: single
