#  _ _     _                                           _           
# | (_)_ _(_)_ _  __ _   _ _ ___  ___ _ __    ___   __| |__ _ _  _ 
# | | \ V / | ' \/ _` | | '_/ _ \/ _ \ '  \  |___| / _` / _` | || |
# |_|_|\_/|_|_||_\__, | |_| \___/\___/_|_|_|       \__,_\__,_|\_, |
#                |___/                                        |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Living Room Day'
description: 'Automation to activate living room day time scene.'
mode: single
trigger: []
condition: []
action:
  - parallel:
      - if:
          - condition: state
            entity_id: light.living_room_dreamview
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.living_room_dreamview
      - if:
          - condition: state
            entity_id: light.living_room_lava_lamp
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.living_room_lava_lamp
      - service: light.turn_on
        data:
          transition: 10
          rgb_color:
            - 255
            - 127
            - 0
          brightness: 255
        target:
          entity_id:
            - light.living_room_display_leds
            - light.living_room_tv_leds
            - light.living_room_leds
