#  _ _     _                                                      _       _   _           
# | (_)_ _(_)_ _  __ _   _ _ ___  ___ _ __    ___   _ __  _____ _(_)___  | |_(_)_ __  ___ 
# | | \ V / | ' \/ _` | | '_/ _ \/ _ \ '  \  |___| | '  \/ _ \ V / / -_) |  _| | '  \/ -_)
# |_|_|\_/|_|_||_\__, | |_| \___/\___/_|_|_|       |_|_|_\___/\_/|_\___|  \__|_|_|_|_\___|
#                |___/                                                                    
#--FROM https://github.com/smcnab1/op-question-mark

alias: Lighting Living Room Movie Time
description: 'Automation automatically turn on movie scene when TV is turned on to certain apps/channels.'
trigger:
  - platform: state
    entity_id:
    - media_player.living_room_tv
    attribute: source
    to: Disney+
  - platform: state
    entity_id:
    - media_player.living_room_tv
    attribute: source
    to: DVD Player
  - platform: state
    entity_id:
    - media_player.living_room_tv
    attribute: source
    to: Prime Video
  - platform: state
    entity_id:
    - media_player.living_room_tv
    attribute: source
    to: Paramount Plus
  - platform: state
    entity_id:
    - media_player.living_room_tv
    attribute: source
    to: Discovery+
  - platform: state
    entity_id:
    - media_player.living_room_tv
    attribute: source
    to: org.tizen.netflix-app
  - platform: state
    entity_id:
    - media_player.living_room_tv
    to: Netflix
condition: []
action:
  - service: scene.create
    data:
      scene_id: premovie
      snapshot_entities:
      - light.living_room_display_led
      - light.living_room_leds
      - light.living_room_dreamview
      - light.living_room_lava_lamp
      - light.living_room_tv_leds
  - service: automation.trigger
    data:
      skip_condition: false
    target:
      entity_id: automation.living_room_movie
  - service: light.turn_on
    data:
      profile: Video
    target:
      entity_id: light.living_room_dreamview
  - wait_for_trigger:
    - platform: state
      entity_id:
      - media_player.living_room_tv
      to: 'off'
  - service: scene.turn_on
    data:
      transition: 60
    target:
      entity_id: scene.premovie
mode: single
