#  _ _     _                                                      _     
# | (_)_ _(_)_ _  __ _   _ _ ___  ___ _ __    ___   _ __  _____ _(_)___ 
# | | \ V / | ' \/ _` | | '_/ _ \/ _ \ '  \  |___| | '  \/ _ \ V / / -_)
# |_|_|\_/|_|_||_\__, | |_| \___/\___/_|_|_|       |_|_|_\___/\_/|_\___|
#                |___/                                                  
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Living Room Movie'
description: 'Automation to activate living room movie scene.'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 60
    target:
      entity_id: scene.living_room_movie
  - service: light.turn_on
    data:
      profile: Video
    target:
      entity_id: light.living_room_dreamview
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.living_room_main_light_2
      - light.living_room_tv_leds
      - light.living_room_lamp
      - light.all_kitchen_lights
mode: single
