#  _ _     _                                             _      _   _   
# | (_)_ _(_)_ _  __ _   _ _ ___  ___ _ __    ___   _ _ (_)__ _| |_| |_ 
# | | \ V / | ' \/ _` | | '_/ _ \/ _ \ '  \  |___| | ' \| / _` | ' \  _|
# |_|_|\_/|_|_||_\__, | |_| \___/\___/_|_|_|       |_||_|_\__, |_||_\__|
#                |___/                                    |___/         
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Living Room Night'
description: 'Automation to activate living room night time scene.'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.scene_living_room_night
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.living_room_main_light_2
      - light.living_room_dreamview
mode: single
