#  _ _     _                                             _      _   _   
# | (_)_ _(_)_ _  __ _   _ _ ___  ___ _ __    ___   _ _ (_)__ _| |_| |_ 
# | | \ V / | ' \/ _` | | '_/ _ \/ _ \ '  \  |___| | ' \| / _` | ' \  _|
# |_|_|\_/|_|_||_\__, | |_| \___/\___/_|_|_|       |_||_|_\__, |_||_\__|
#                |___/                                    |___/         
#--FROM https://github.com/smcnab1/op-question-mark

alias: Lighting Living Room Night
description: Automation to activate living room night time scene.
trigger: []
condition:
  - condition: state
    entity_id: light.living_room_dreamview
    state: "off"
action:
  - parallel:
      - if:
          - condition: state
            entity_id: light.living_room_main_light
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.living_room_main_light
      - if:
          - condition: state
            entity_id: light.living_room_dreamview
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.living_room_dreamview
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.living_room_lava_lamp
      - service: light.turn_on
        data:
          transition: 10
          rgb_color:
            - 255
            - 0
            - 191
          brightness: 155
        target:
          entity_id:
            - light.living_room_leds
            - light.living_room_tv_leds
            - light.living_room_display_led
mode: single

