#  _ _     _                                             __  __ 
# | (_)_ _(_)_ _  __ _   _ _ ___  ___ _ __    ___   ___ / _|/ _|
# | | \ V / | ' \/ _` | | '_/ _ \/ _ \ '  \  |___| / _ \  _|  _|
# |_|_|\_/|_|_||_\__, | |_| \___/\___/_|_|_|       \___/_| |_|  
#                |___/                                          
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Living Room Off'
description: 'Automation to turn off all living room lights.'
trigger: []
condition: []
action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.all_living_room_lights
mode: single
