#     _ _                                                                          _                            _   _  __      
#  __(_) |_ _  _ _ __  __ _ _ __ _ __  ___ _ _   ___ __ _ _ __    _ _ __ _ _ _  __| |___ _ __    ___   _ _  ___| |_(_)/ _|_  _ 
# / _| |  _| || | '  \/ _` | '_ \ '_ \/ -_) '_| (_-</ _` | '  \  | '_/ _` | ' \/ _` / _ \ '  \  |___| | ' \/ _ \  _| |  _| || |
# \__|_|\__|\_, |_|_|_\__,_| .__/ .__/\___|_|   /__/\__,_|_|_|_| |_| \__,_|_||_\__,_\___/_|_|_|       |_||_\___/\__|_|_|  \_, |
#           |__/           |_|  |_|                                                                                       |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: Transport Citymapper Notify Sam Random
description: 'Automation triggered by dashboard pushing actionable notification to my phone to input end location from current location on the Citymapper Mobile App.'
trigger: []
condition:
  - condition: state
    entity_id: person.sam
    state: home
action:
  - service: notify.mobile_app_iphone
    data:
      title: Want help getting somewhere?
      message: Open Citymapper
      data:
        actions:
        - action: OPEN
          title: Navigate
          uri: !secret citymapper_sam_home_to
          icon: sfsymbols:tram.fill.tunnel
mode: single
