#     _ _                                        _          _                     _                    _   _  __      
#  __(_) |_ _  _ _ __  __ _ _ __ _ __  ___ _ _  | |___ __ _| |_   __ __ _____ _ _| |__  ___   _ _  ___| |_(_)/ _|_  _ 
# / _| |  _| || | '  \/ _` | '_ \ '_ \/ -_) '_| | / -_) _` | ' \  \ V  V / _ \ '_| / / |___| | ' \/ _ \  _| |  _| || |
# \__|_|\__|\_, |_|_|_\__,_| .__/ .__/\___|_|   |_\___\__,_|_||_|  \_/\_/\___/_| |_\_\       |_||_\___/\__|_|_|  \_, |
#           |__/           |_|  |_|                                                                              |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: Transport Citymapper Notify Leah Work
description: 'Automation triggered by dashboard pushing actionable notification to wifes phone to work which auto populates directions from current location on the Citymapper Mobile App.'
trigger: []
condition:
  - condition: state
    entity_id: person.leah
    state: home
action:
  - service: notify.mobile_app_leah_s_iphone
    data:
      title: Want help getting to work?
      message: Open Citymapper
      data:
        actions:
        - action: OPEN
          title: Work
          uri: !secret citymapper_leah_home_to_work
          icon: sfsymbols:h.square.fill
mode: single
