#                                                         _                            _   _  __      
# __ __ ____ _ ______   ___ __ _ _ __    _ _ __ _ _ _  __| |___ _ __    ___   _ _  ___| |_(_)/ _|_  _ 
# \ V  V / _` |_ / -_) (_-</ _` | '  \  | '_/ _` | ' \/ _` / _ \ '  \  |___| | ' \/ _ \  _| |  _| || |
#  \_/\_/\__,_/__\___| /__/\__,_|_|_|_| |_| \__,_|_||_\__,_\___/_|_|_|       |_||_\___/\__|_|_|  \_, |
#                                                                                                |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: Transport Waze Random
description: 'Automation triggered by dashboard pushing actionable notification to my phone that automatically navigates to the search page of the Waze Mobile App.'
trigger: []
condition: []
action:
  - service: notify.mobile_app_sams_iphone
    data:
      data:
        actions:
        - action: OPEN
          title: Open Waze
          uri: !secret waze_random
      message: Want help getting somewhere?
mode: single
