#  _          _   _                               _          _   _    
# | |__  __ _| |_| |_  _ _ ___  ___ _ __    ___  | |__  __ _| |_| |_  
# | '_ \/ _` |  _| ' \| '_/ _ \/ _ \ '  \  |___| | '_ \/ _` |  _| ' \ 
# |_.__/\__,_|\__|_||_|_| \___/\___/_|_|_|       |_.__/\__,_|\__|_||_|
#                                                                     
#--FROM https://github.com/smcnab1/op-question-mark

alias: Lighting Bathroom Bath
description: Automation to activate bath time scene.
mode: single
trigger: []
condition: []
action:
  - service: light.turn_on
    data:
      transition: 60
      brightness: 117
      hs_color:
        - 2
        - 100
      xy_color:
        - 0.699
        - 0.3
      rgb_color:
        - 255
        - 8
        - 0
    target:
      entity_id: light.bathroom_main_lights

