#  _          _   _                                                  _           
# | |__  __ _| |_| |_  _ _ ___  ___ _ __    ___   _ __  ___ _ _ _ _ (_)_ _  __ _ 
# | '_ \/ _` |  _| ' \| '_/ _ \/ _ \ '  \  |___| | '  \/ _ \ '_| ' \| | ' \/ _` |
# |_.__/\__,_|\__|_||_|_| \___/\___/_|_|_|       |_|_|_\___/_| |_||_|_|_||_\__, |
#                                                                          |___/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Bathroom Morning'
description: Automation to activate morning bathroom scene.
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 30
    target:
      entity_id: scene.scene_bathroom_morning
mode: single
