name: ⚙️ Feature Request
description: Suggest an idea for this project
title: "[FR] "
labels: [⚙️Type: Feature, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing feature request for this?
    description: Please search to see if a feature request already exists for the suggestion you have.
    options:
    - label: I have searched the existing feature requests
      required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the problem is.
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the suggestion you have!

  validations:
    required: false
