id: '1660674410898'
name: 'Scene: Office Gaming'
entities:
  light.office_desk_led:
    supported_color_modes:
    - hs
    color_mode: hs
    brightness: 181
    hs_color:
    - 120
    - 100
    rgb_color:
    - 0
    - 255
    - 0
    xy_color:
    - 0.172
    - 0.747
    friendly_name: 'Office: Desk LED'
    supported_features: 0
    state: 'on'
icon: mdi:microsoft-xbox
metadata:
  light.office_desk_led:
    entity_only: true
