#  _   _        _                _           _            _                    
# | |_| |_ ___ (_)_ _  _ __ _  _| |_   ___  | |__  ___ __| |_ _ ___  ___ _ __  
# |  _|  _(_-< | | ' \| '_ \ || |  _| |___| | '_ \/ -_) _` | '_/ _ \/ _ \ '  \ 
#  \__|\__/__/ |_|_||_| .__/\_,_|\__|       |_.__/\___\__,_|_| \___/\___/_|_|_|
#                     |_|                                                      
#--FROM https://github.com/smcnab1/op-question-mark

alias: TTS Input Push Bedroom
description: Automation that sends input from HA Dashboard to Google Hub Mini's as TTS Message.
trigger: []
condition: []
action:
  - data_template:
      entity_id: media_player.bedroom
      message: '{{ states(''input_text.tts_message_bedroom'') }}'
    service: tts.cloud_say
mode: single
