#  _   _        _                _           _         _ _ 
# | |_| |_ ___ (_)_ _  _ __ _  _| |_   ___  | |_  __ _| | |
# |  _|  _(_-< | | ' \| '_ \ || |  _| |___| | ' \/ _` | | |
#  \__|\__/__/ |_|_||_| .__/\_,_|\__|       |_||_\__,_|_|_|
#                     |_|                                  
#--FROM https://github.com/smcnab1/op-question-mark

alias: TTS Input Push Hall
description: Automation that sends input from HA Dashboard to Fully Browser Android Tablet as TTS Message.
trigger: []
condition: []
action:
  - data_template:
      entity_id: media_player.dashboard_tablet
      message: '{{ states(''input_text.tts_message_hall'') }}'
    service: tts.cloud_say
mode: single