id: '1660667031853'
alias: 'Scene: Office Lamp'
description: ''
trigger: []
condition: []
action:
- service: scene.turn_on
  data:
    transition: 30
  target:
    entity_id: scene.scene_office_lamp
mode: single
