id: '1659722448645'
alias: 'Alarm: Arm Option Notification - Sam'
description: ''
trigger:
- platform: state
  entity_id:
  - person.sam_mcnab
  to: away
condition: []
action:
- service: notify.mobile_app_sam_s_phone
  data:
    message: Would you like to set it?
    title: Set Alarm?
    data:
      icon:
      ttl: 0
      visibility: public
      push:
        sound:
          volume: 1
      actions:
      - action: IGNORE
        title: Don't Arm Alarm
      - action: ARM_ALARM
        title: Arm Alarm
mode: single
