#  _         _ _            _           
# | |_  __ _| | |  ___   __| |__ _ _  _ 
# | ' \/ _` | | | |___| / _` / _` | || |
# |_||_\__,_|_|_|       \__,_\__,_|\_, |
#                                  |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Hall Day'
description: 'Automation to activate hallway day time scene.'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 20
    target:
      entity_id: scene.scene_hall_day
mode: single
