#  _         _ _              _      _   _   
# | |_  __ _| | |  ___   _ _ (_)__ _| |_| |_ 
# | ' \/ _` | | | |___| | ' \| / _` | ' \  _|
# |_||_\__,_|_|_|       |_||_|_\__, |_||_\__|
#                              |___/         
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Hall Night'
description: 'Automation to activate hallway night time scene.'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 20
    target:
      entity_id: scene.hall_night
mode: single
