#  _         _ _              __  __ 
# | |_  __ _| | |  ___   ___ / _|/ _|
# | ' \/ _` | | | |___| / _ \  _|  _|
# |_||_\__,_|_|_|       \___/_| |_|  
#                                    
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Hall Off'
description: 'Automation to turn off all hall lights.'
trigger: []
condition: []
action:
  - parallel:
      - if:
          - condition: state
            entity_id: light.hall_lamp
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.hall_lamp
      - if:
          - condition: state
            entity_id: light.hall_leds
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.hall_leds
      - if:
          - condition: state
            entity_id: light.hall_main_lights
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.hall_main_lights
mode: single

