#  _         _ _              __  __ 
# | |_  __ _| | |  ___   ___ / _|/ _|
# | ' \/ _` | | | |___| / _ \  _|  _|
# |_||_\__,_|_|_|       \___/_| |_|  
#                                    
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Hall Off'
description: 'Automation to turn off all hall lights.'
trigger: []
condition: []
action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.all_hall_lights
mode: single
