#  _         _ _            _              
# | |_  __ _| | |  ___   __| |___ ___ _ __ 
# | ' \/ _` | | | |___| (_-< / -_) -_) '_ \
# |_||_\__,_|_|_|       /__/_\___\___| .__/
#                                    |_|   
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Hall Sleep'
description: 'Automation to activate hallway sleeping scene when going for a pee at night.'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 20
    target:
      entity_id: scene.scene_hall_sleep
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.hall_lamp
mode: single
