---
### Card Input Boolean ###
card_party_activate:
  template:
    - "icon_more_info_new"
    - "ulm_translation_engine"
  variables:
    ulm_card_input_boolean_icon: "[[[ return entity.attributes.icon ]]]"
    ulm_card_input_boolean_name: "[[[ return entity.attributes.friendly_name ]]]"
  tap_action:
    action: toggle
  custom_fields:
    item1:
      card:
        type: "custom:button-card"
        template:
          - "blue"
        tap_action:
          action: toggle
        custom_fields:
          item1:
            card:
              type: "custom:button-card"
              entity: "[[[ return entity.entity_id ]]]"
              icon: "[[[ return variables.ulm_card_input_boolean_icon; ]]]"
              state:
                - value: 'on'
                  styles:
                    icon:
                      - animation:
                          - rotating 1s linear infinite
                      - color: |
                          [[[
                              return "rgb(" + states['light.kitchen_leds'].attributes.rgb_color + ")";
                          ]]]
              tap_action:
                action: toggle
          item2:
            card:
              type: "custom:button-card"
              entity: input_boolean.party
              name: "[[[ return variables.ulm_card_input_boolean_name; ]]]"
              label: "[[[ return variables.ulm_translation_state ]]]"
              state:
                - value: 'on'
                  styles:
                    name:
                      - color: |
                          [[[
                              return "rgb(" + states['light.kitchen_leds'].attributes.rgb_color + ")";
                          ]]]
              tap_action:
                action: toggle
