#  _            _                               _           
# | |__  ___ __| |_ _ ___  ___ _ __    ___   __| |__ _ _  _ 
# | '_ \/ -_) _` | '_/ _ \/ _ \ '  \  |___| / _` / _` | || |
# |_.__/\___\__,_|_| \___/\___/_|_|_|       \__,_\__,_|\_, |
#                                                      |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Bedroom Day'
description: 'Automation to activate day time bedroom scene.'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.scene_bedroom_day
mode: single
