#  _            _                               _           
# | |__  ___ __| |_ _ ___  ___ _ __    ___   __| |__ _ _  _ 
# | '_ \/ -_) _` | '_/ _ \/ _ \ '  \  |___| / _` / _` | || |
# |_.__/\___\__,_|_| \___/\___/_|_|_|       \__,_\__,_|\_, |
#                                                      |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Bedroom Day'
description: 'Automation to activate day time bedroom scene.'
mode: single
trigger: []
condition: []
action:
  - parallel:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.bedroom_main_light
      - service: light.turn_on
        data:
          brightness: 255
          rgb_color:
            - 255
            - 127
            - 0
          transition: 10
        target:
          entity_id: light.bedroom_leds
      - if:
          - condition: state
            entity_id: light.bedroom_fairy_lights
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.bedroom_fairy_lights
      - if:
          - condition: state
            entity_id: light.bedside_leah
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.bedside_leah
      - if:
          - condition: state
            entity_id: light.bedside_sam
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.bedside_sam
