#  _            _                                          _       _   _
# | |__  ___ __| |_ _ ___  ___ _ __    ___   _ __  _____ _(_)___  | |_(_)_ __  ___
# | '_ \/ -_) _` | '_/ _ \/ _ \ '  \  |___| | '  \/ _ \ V / / -_) |  _| | '  \/ -_)
# |_.__/\___\__,_|_| \___/\___/_|_|_|       |_|_|_\___/\_/|_\___|  \__|_|_|_|_\___|
#
#--FROM https://github.com/smcnab1/op-question-mark

alias: Lighting Bedroom Movie Time
description: >-
  Automation automatically turn on Movie Scene when TV is turned on to certain
  apps/channels.
trigger:
  - platform: state
    entity_id:
      - media_player.bedroom_tv
    to: playing
    id: "ON"
  - platform: state
    entity_id:
      - media_player.bedroom_tv
    to: paused
    id: pause
  - platform: state
    entity_id:
      - media_player.bedroom_tv
    to: "off"
    id: "off"
condition: []
action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: "ON"
        sequence:
          - service: scene.create
            data:
              scene_id: prebedmovie
              snapshot_entities:
                - light.bedroom_main_light
                - light.bedroom_leds
                - light.bedside_lamps
                - light.bedroom_fairy_lights
          - service: automation.trigger
            data:
              skip_condition: false
            target:
              entity_id: automation.lighting_bedroom_movie
      - conditions:
          - condition: trigger
            id: pause
        sequence:
          - service: light.turn_on
            data:
              transition: 15
              brightness: 10
            target:
              entity_id: light.bedside_lamps
      - conditions:
          - condition: trigger
            id: "ON"
        sequence:
          - service: automation.trigger
            data:
              skip_condition: false
            target:
              entity_id: automation.lighting_bedroom_movie
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - delay:
              hours: 0
              minutes: 0
              seconds: 30
              milliseconds: 0
          - if:
              - condition: state
                entity_id: input_boolean.all_sleeping
                state: "on"
            then:
              - service: automation.trigger
                data:
                  skip_condition: false
                target:
                  entity_id: automation.lighting_bedroom_off
            else:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.prebedmovie
mode: single
