#  _            _                                 _      _   _   
# | |__  ___ __| |_ _ ___  ___ _ __    ___   _ _ (_)__ _| |_| |_ 
# | '_ \/ -_) _` | '_/ _ \/ _ \ '  \  |___| | ' \| / _` | ' \  _|
# |_.__/\___\__,_|_| \___/\___/_|_|_|       |_||_|_\__, |_||_\__|
#                                                  |___/         
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Bedroom Night'
description: 'Automation to activate bedroom night time scene.'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.scene_bedroom_night
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.bedroom
mode: single
