#  _            _                                 _      _   _
# | |__  ___ __| |_ _ ___  ___ _ __    ___   _ _ (_)__ _| |_| |_
# | '_ \/ -_) _` | '_/ _ \/ _ \ '  \  |___| | ' \| / _` | ' \  _|
# |_.__/\___\__,_|_| \___/\___/_|_|_|       |_||_|_\__, |_||_\__|
#                                                  |___/
#--FROM https://github.com/smcnab1/op-question-mark

alias: "Lighting Bedroom Night"
description: "Automation to activate bedroom night time scene."
mode: single
trigger: []
condition: []
action:
  - parallel:
      - service: light.turn_on
        data:
          transition: 10
          rgb_color:
            - 255
            - 127
            - 0
          brightness: 128
        target:
          entity_id: light.bedroom_leds
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.bedside_lamps
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.bedroom_fairy_lights
      - if:
          - condition: state
            entity_id: light.bedroom_main_light
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.bedroom_main_light
