#  _            _                                 __  __ 
# | |__  ___ __| |_ _ ___  ___ _ __    ___   ___ / _|/ _|
# | '_ \/ -_) _` | '_/ _ \/ _ \ '  \  |___| / _ \  _|  _|
# |_.__/\___\__,_|_| \___/\___/_|_|_|       \___/_| |_|  
#                                                        
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Bedroom Off'
description: 'Automation to turn off all bedroom lights.'
trigger: []
condition: []
action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.all_bedroom_lights
mode: single
