id: '1661421293401'
alias: Holiday Mode OFF
description: ''
trigger:
- platform: state
  entity_id:
  - input_boolean.holiday
  to: 'off'
condition: []
action:
- service: automation.turn_on
  data: {}
  target:
    entity_id:
    - automation.car_wash_wash_car_notification
    - automation.welcome_home
    - automation.waze_islington
    - automation.waze_camden
    - automation.update_notifications
    - automation.tv_control
    - automation.turn_all_lights_off
    - automation.tag_alarm_disarm_is_scanned
    - automation.tag_alarm_arm_if_scanned
    - automation.scene_bathroom_morning
    - automation.scene_bathroom_normal
    - automation.scene_bathroom_off
    - automation.scene_bedroom_day
    - automation.scene_bedroom_movie
    - automation.scene_bedroom_night
    - automation.scene_bedroom_off
    - automation.scene_hall_day
    - automation.scene_hall_sleep
    - automation.scene_hall_night_2
    - automation.scene_kitchen_cooking
    - automation.scene_office_off
    - automation.scene_office_lamp
    - automation.scene_office_gaming
    - automation.scene_office_dull
    - automation.scene_office_bright
    - automation.scene_living_room_off
    - automation.bedroom_daytime
mode: single
