#  _   _ _      _                                 _   _           
# | |_(_) |_ __| |_  ___ _ _    ___   __ ___  ___| |_(_)_ _  __ _ 
# | / / |  _/ _| ' \/ -_) ' \  |___| / _/ _ \/ _ \ / / | ' \/ _` |
# |_\_\_|\__\__|_||_\___|_||_|       \__\___/\___/_\_\_|_||_\__, |
#                                                           |___/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Kitchen Cooking'
description: 'Automation to activate kitchen cooking scene during certain times.'
mode: single
trigger: []
condition: []
action:
  - parallel:
      - service: light.turn_on
        data:
          transition: 10
          brightness: 177
        target:
          entity_id:
            - light.kitchen_main_lights
      - service: light.turn_on
        data:
          transition: 10
          rgb_color:
            - 255
            - 255
            - 255
          brightness: 178
        target:
          entity_id: light.kitchen_leds
