#  _   _ _      _                                             _ 
# | |_(_) |_ __| |_  ___ _ _    ___   _ _  ___ _ _ _ __  __ _| |
# | / / |  _/ _| ' \/ -_) ' \  |___| | ' \/ _ \ '_| '  \/ _` | |
# |_\_\_|\__\__|_||_\___|_||_|       |_||_\___/_| |_|_|_\__,_|_|
#                                                               
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Kitchen Normal'
description: 'Automation to activate normal kitchen scene.'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 20
    target:
      entity_id: scene.kitchen_normal
  - service: light.turn_off
    data:
      transition: 20
    target:
      entity_id: light.kitchen_lights
mode: single
