#  _   _ _      _                                             _ 
# | |_(_) |_ __| |_  ___ _ _    ___   _ _  ___ _ _ _ __  __ _| |
# | / / |  _/ _| ' \/ -_) ' \  |___| | ' \/ _ \ '_| '  \/ _` | |
# |_\_\_|\__\__|_||_\___|_||_|       |_||_\___/_| |_|_|_\__,_|_|
#                                                               
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Kitchen Normal'
description: 'Automation to activate normal kitchen scene.'
mode: single
trigger: []
condition: []
action:
  - parallel:
      - service: light.turn_on
        data:
          transition: 10
          rgb_color:
            - 255
            - 127
            - 0
          brightness: 178
        target:
          entity_id: light.kitchen_leds
