#  _   _ _      _                          __  __ 
# | |_(_) |_ __| |_  ___ _ _    ___   ___ / _|/ _|
# | / / |  _/ _| ' \/ -_) ' \  |___| / _ \  _|  _|
# |_\_\_|\__\__|_||_\___|_||_|       \___/_| |_|  
#                                                 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Kitchen Off'
description: 'Automation to turn off all kitchen lights.'
trigger: []
condition: []
action:
  - parallel:
      - if:
          - condition: state
            entity_id: light.kitchen_leds
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.kitchen_leds
      - if:
          - condition: state
            entity_id: light.kitchen_main_lights
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.kitchen_main_lights
mode: single
