#  _   _ _      _                          __  __ 
# | |_(_) |_ __| |_  ___ _ _    ___   ___ / _|/ _|
# | / / |  _/ _| ' \/ -_) ' \  |___| / _ \  _|  _|
# |_\_\_|\__\__|_||_\___|_||_|       \___/_| |_|  
#                                                 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Kitchen Off'
description: 'Automation to turn off all kitchen lights.'
trigger: []
condition: []
action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.all_kitchen_lights
mode: single
