
alias: 'Scene: Bathroom Off'
description: ''
trigger: []
condition: []
action:
  - service: light.turn_off
    data:
      transition: 30
    target:
      entity_id: light.all_bathroom_lights
mode: single
