
alias: 'Scene: Bathroom Bath'
description: ''
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 30
    target:
      entity_id: scene.scene_bathroom_bath
mode: single
