
alias: 'Scene: Bedroom Night'
description: ''
trigger: []
condition: []
action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.scene_bedroom_night
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.bedroom
mode: single
