
alias: 'Scene: Bedroom Movie'
description: ''
trigger: []
condition: []
action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.scene_bedroom_movie
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bedroom
      - light.bedside_lamps
mode: single
