
alias: 'Car Wash: Wash Car Notification'
description: ''
trigger:
  - platform: state
    entity_id:
    - binary_sensor.car_wash
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.holiday
    state: 'off'
action:
  - service: notify.mobile_app_iphone
    data:
      title: Wash Your Car
      message: What would you like to do?
      data:
        ttl: 0
        icon: mdi:car-wash
        actions:
        - action: OPEN
          title: Navigate to Local Car Wash
          uri: https://waze.com/ul/?ll=51.54787782194006%2C-0.1840422629292826&navigate=yes&zoom=17
        - action: OPEN
          title: Book Car Wash Visit
          uri: https://apps.apple.com/gb/app/splash-and-drip/id1594348529
mode: single