alias: "Alarm: Disarm Alarm Action - Leah"
description: ""
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: DISARM_ALARM
    context:
      user_id:
        - d5de2d519885447495a552f1d87f0a9d
condition: []
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      code: "1550"
    target:
      entity_id: alarm_control_panel.home_alarm
  - service: notify.notify
    data:
      title: ALARM DISARMED
      message: The Alarm was Disarmed by Leah
mode: single
