
alias: 'Alarm: Disarm Alarm Action - Sam'
description: ''
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: DISARM_ALARM
    context:
      user_id:
      - 47cefae3ba0f490c8ccafd6bfedad232
condition: []
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      code: '1550'
    target:
      entity_id: alarm_control_panel.home_alarm
  - service: notify.notify
    data:
      title: ALARM DISARMED
      message: The Alarm was Disarmed by Sam
mode: single
