alias: Home Assistant Restart Complete
description: ""
mode: single
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - parallel:
      - if:
          - condition: state
            entity_id: binary_sensor.sam_s_mac_mini_active
            state: "on"
        then:
          - service: notify.mobile_app_sam_s_mac_mini
            data:
              title: Home Assistant - System Management
              message: Home Assistant has Restarted
              data:
                actions:
                  - action: OPEN
                    title: Open Home Assistant
                    uri: "http://homeassistant.local:8123/"
                    icon: sfsymbols:safari
      - if:
          - condition: state
            entity_id: person.presence
            state: home
        then:
          - service: tts.cloud_say
            data:
              message: >-
                Home Assistant is back up. Things should work now. Not so silly
                now
              entity_id: media_player.living_room_speaker
          - service: tts.cloud_say
            data:
              message: >-
                Home Assistant is back up. Things should work now. Not so silly
                now
              entity_id: media_player.bedroom
