
alias: 'Scene: Hall Night'
description: ''
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 20
    target:
      entity_id: scene.scene_hall_night
mode: single
