
alias: 'Scene: Kitchen Off'
description: ''
trigger: []
condition: []
action:
  - service: light.turn_off
    data:
      transition: 20
    target:
      entity_id: light.all_kitchen_lights
mode: single
