
alias: 'Scene: Living Room Movie'
description: ''
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 60
    target:
      entity_id: scene.scene_living_room_movie
  - service: light.turn_on
    data:
      profile: Video
    target:
      entity_id: light.living_room_dreamview
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.living_room
      - light.living_room_tv_leds
      - light.living_room_lamp
      - light.all_kitchen_lights
mode: single
