id: '1660667734748'
alias: 'Scene: Living Room Night'
description: ''
trigger: []
condition: []
action:
- service: scene.turn_on
  data: {}
  target:
    entity_id: scene.scene_living_room_night
- service: light.turn_off
  data: {}
  target:
    entity_id:
    - light.living_room
    - light.living_room_dreamview
mode: single
