id: '1660688037801'
alias: Movie Time - Living Room
description: ''
trigger:
- platform: state
  entity_id:
  - media_player.samsung_tv
  attribute: source
  to: Disney+
- platform: state
  entity_id:
  - media_player.samsung_tv
  attribute: source
  to: DVD Player
- platform: state
  entity_id:
  - media_player.samsung_tv
  attribute: source
  to: Prime Video
- platform: state
  entity_id:
  - media_player.samsung_tv
  attribute: source
  to: Paramount Plus
- platform: state
  entity_id:
  - media_player.samsung_tv
  attribute: source
  to: Discovery+
- platform: state
  entity_id:
  - media_player.samsung_tv
  attribute: source
  to: org.tizen.netflix-app
- platform: state
  entity_id:
  - media_player.samsung_tv
  to: Netflix
condition: []
action:
- service: scene.create
  data:
    scene_id: premovie
    snapshot_entities:
    - light.living_room_dining_led
    - light.living_room_leds
    - light.living_room
    - light.living_room_dreamview
    - light.living_room_lamp
    - light.lava_lamp
    - light.living_room_tv_leds
- service: automation.trigger
  data:
    skip_condition: false
  target:
    entity_id: automation.scene_living_room_movie
- service: light.turn_on
  data:
    profile: Video
  target:
    entity_id: light.living_room_dreamview
- wait_for_trigger:
  - platform: state
    entity_id:
    - media_player.samsung_tv
    to: 'off'
- service: scene.turn_on
  data:
    transition: 60
  target:
    entity_id: scene.premovie
mode: single
