
alias: Movie Time - Bedroom
description: ''
trigger:
  - platform: state
    entity_id:
    - media_player.fire_tv_192_168_1_104
    to: playing
condition: []
action:
  - service: scene.create
    data:
      scene_id: prebedmovie
      snapshot_entities:
      - light.bedroom
      - light.bedroom_leds
      - light.bedside_lamps
  - service: automation.trigger
    data:
      skip_condition: false
    target:
      entity_id: automation.scene_bedroom_movie
  - wait_for_trigger:
    - platform: state
      entity_id:
      - media_player.fire_tv_192_168_1_104
      to: off
  - service: scene.turn_on
    data:
      transition: 60
    target:
      entity_id: scene.prebedmovie
mode: single
