
alias: 'Scene: Office Dull'
description: ''
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 30
    target:
      entity_id: scene.scene_office_dull
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.desk_lamp
mode: single
