alias: Tablet Charging
description: ""
mode: single
trigger: []
condition: []
action:
  - if:
      - condition: numeric_state
        entity_id: sensor.foo_battery_level
        below: "40"
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.sonoff_100149c411_1
    else:
      - wait_for_trigger:
          - platform: numeric_state
            entity_id: sensor.foo_battery_level
            above: "90"
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.sonoff_100149c411_1
