id: '1658408646595'
alias: 'Tag: Turn OFF Lights if scanned'
description: ''
trigger:
- platform: tag
  tag_id: 09b945be-22fe-42cd-addb-77e9e40a0a9f
- platform: tag
  tag_id: 3e0bd108-211c-4220-b379-7b6eac6851be
condition: []
action:
- service: light.turn_off
  data: {}
  target:
    area_id:
    - bedroom
    - hall
    - kitchen
    - living_room
mode: single
