id: '1658409071632'
alias: 'Tag: Desk Lamp ON if scanned'
description: ''
trigger:
- platform: tag
  tag_id: d779b88d-464d-4b8b-96fe-cb4ea167bf63
condition: []
action:
- service: light.toggle
  data: {}
  target:
    entity_id: light.office_desk_led
mode: single
