
alias: Tag Alarm DISARM is scanned
description: ''
trigger:
  - platform: tag
    tag_id: 96b80282-cc2f-4d75-93c4-483d464f25c0
condition: []
action:
  - service: alarm_control_panel.alarm_disarm
    data: {}
    target:
      entity_id:
      - alarm_control_panel.home_alarm
mode: single
