
alias: 'Alarm: Trigger Notification - Sam'
description: ''
trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.home_alarm
    to: triggered
action:
  - service: notify.mobile_app_iphone
    data:
      title: INTRUDER ALERT - HOME ALARM TRIGGERED
      message: What would you like to do?
      data:
        sticky: 'true'
        ttl: 0
        importance: high
        persistent: true
        tag: persistent
        visibility: public
        push:
          sound:
            name: 3rd_party_critical.caf
            critical: 1
            volume: 1
          interruption-level: critical
          presentation_options:
          - alert
        actions:
        - action: URI
          title: View Cameras
          uri: /ui-lovelace-minimalist/secure
          icon: sfsymbols:camera.circle.fill
        - action: URI
          title: Text Leah
          uri: https://api.whatsapp.com/send?phone=+447531049994&text=Alarm%20has%20gone%20off%0EYou%20at%20home%1F#Intent;package=com.whatsapp;scheme=whatsapp;end&phone=+447513595678
          icon: "sfsymbols:phone.circle.fill"
        - action: DISARM_ALARM
          title: Disarm
          icon: sfsymbols:bell.fill
          destructive: true
        - action: CALL
          title: Call the Police
          uri: tel:999
          icon: sfsymbols:phone.fill
          destructive: true
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: notify.mobile_app_iphone
    data:
      message: clear_notification
mode: single
