id: '1659650344252'
alias: 'Alarm: Trigger Notification - Sam'
description: ''
trigger:
- platform: state
  entity_id:
  - alarm_control_panel.home_alarm
  to: triggered
  enabled: true
condition: []
action:
- service: notify.mobile_app_sam_s_phone
  data:
    message: command_ringer_mode
    title: normal
- delay:
    hours: 0
    minutes: 0
    seconds: 1
    milliseconds: 0
- service: notify.mobile_app_sam_s_phone
  data:
    message: command_screen_on
    title: keep_screen_on
- service: notify.mobile_app_sam_s_phone
  data:
    message: TTS
    title: INTRUDER ALERT - HOME ALARM TRIGGERED
    data:
      data:
        ttl: 0
        priority: high
        channel: alarm_stream
- service: notify.mobile_app_sam_s_phone
  data:
    title: INTRUDER ALERT - HOME ALARM TRIGGERED
    message: What would you like to do?
    data:
      sticky: 'true'
      color: red
      icon:
      ttl: 0
      importance: high
      persistent: true
      tag: persistent
      visibility: public
      notification_icon: mdi:alert
      actions:
      - action: URI
        title: View Cameras
        uri: /ui-lovelace-minimalist/secure
      - action: URI
        title: Text Leah
        uri: https://api.whatsapp.com/send?phone=+447531049994&text=Alarm%20has%20gone%20off%0EYou%20at%20home%1F#Intent;package=com.whatsapp;scheme=whatsapp;end&phone=+447513595678
      - action: DISARM_ALARM
        title: Disarm
- delay:
    hours: 0
    minutes: 5
    seconds: 0
    milliseconds: 0
- service: notify.mobile_app_sam_s_phone
  data:
    message: clear_notification
    data:
      tag: persistent
mode: single
