
alias: Text Input for TTS Living Room
trigger: []
condition: []
action:
  - data_template:
      entity_id: media_player.living_room_speaker
      message: '{{ states(''input_text.tts_message'') }}'
    service: tts.cloud_say
