#       __  __ _                _        _      _   _   
#  ___ / _|/ _(_)__ ___   ___  | |__ _ _(_)__ _| |_| |_ 
# / _ \  _|  _| / _/ -_) |___| | '_ \ '_| / _` | ' \  _|
# \___/_| |_| |_\__\___|       |_.__/_| |_\__, |_||_\__|
#                                         |___/         
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Office Bright'
description: 'Automation to activate bright office scene.'
trigger: []
condition: []
action:
  - parallel:
      - service: light.turn_on
        data:
          transition: 10
          rgb_color:
            - 194
            - 223
            - 255
          brightness: 181
        target:
          entity_id:
            - light.office_leds
mode: single
