#       __  __ _                   _        _     _                   _             
#  ___ / _|/ _(_)__ ___   ___   __| |___ __| |__ | |__ _ _ __  _ __  | |_ __ _ __ _ 
# / _ \  _|  _| / _/ -_) |___| / _` / -_|_-< / / | / _` | '  \| '_ \ |  _/ _` / _` |
# \___/_| |_| |_\__\___|       \__,_\___/__/_\_\ |_\__,_|_|_|_| .__/  \__\__,_\__, |
#                                                             |_|             |___/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Office Desk Lamp Tag'
description: 'NFC Tag used to easily turn on the desk lamp'
trigger:
  - platform: tag
    tag_id: d779b88d-464d-4b8b-96fe-cb4ea167bf63
condition: []
action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.office_desk_led
mode: single
