#       __  __ _                   _      _ _ 
#  ___ / _|/ _(_)__ ___   ___   __| |_  _| | |
# / _ \  _|  _| / _/ -_) |___| / _` | || | | |
# \___/_| |_| |_\__\___|       \__,_|\_,_|_|_|
#                                             
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Office Dull'
description: 'Automation to activate dull office scene.'
trigger: []
condition:
  - condition: state
    entity_id: binary_sensor.xbox_status
    state: "off"
action:
  - parallel:
      - service: light.turn_on
        data:
          transition: 10
          rgb_color:
            - 0
            - 191
            - 255
          brightness: 143
        target:
          entity_id:
            - light.office_desk_leds
mode: single
