#       __  __ _                   _      _ _ 
#  ___ / _|/ _(_)__ ___   ___   __| |_  _| | |
# / _ \  _|  _| / _/ -_) |___| / _` | || | | |
# \___/_| |_| |_\__\___|       \__,_|\_,_|_|_|
#                                             
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Office Dull'
description: 'Automation to activate dull office scene.'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 30
    target:
      entity_id: scene.office_dull
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.office_desk_lamp
mode: single
