#       __  __ _                                _           
#  ___ / _|/ _(_)__ ___   ___   __ _ __ _ _ __ (_)_ _  __ _ 
# / _ \  _|  _| / _/ -_) |___| / _` / _` | '  \| | ' \/ _` |
# \___/_| |_| |_\__\___|       \__, \__,_|_|_|_|_|_||_\__, |
#                              |___/                  |___/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Office Gaming'
description: 'Automation to activate gaming scene when xbox turned on.'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 30
    target:
      entity_id: scene.office_gaming
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.office_desk_lamp
mode: single
