#       __  __ _                _                 
#  ___ / _|/ _(_)__ ___   ___  | |__ _ _ __  _ __ 
# / _ \  _|  _| / _/ -_) |___| | / _` | '  \| '_ \
# \___/_| |_| |_\__\___|       |_\__,_|_|_|_| .__/
#                                           |_|   
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Office Lamp'
description: 'Automation to activate bright office scene with desk lamp'
trigger: []
condition: []
action:
  - service: scene.turn_on
    data:
      transition: 30
    target:
      entity_id: scene.scene_office_lamp
mode: single
