#       __  __ _                              _   _           
#  ___ / _|/ _(_)__ ___   ___   _ __  ___ ___| |_(_)_ _  __ _ 
# / _ \  _|  _| / _/ -_) |___| | '  \/ -_) -_)  _| | ' \/ _` |
# \___/_| |_| |_\__\___|       |_|_|_\___\___|\__|_|_||_\__, |
#                                                       |___/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Office Meeting'
description: 'Automation to activate when in meeting to trigger red lights scene.'
trigger: []
condition: []
action:
  - parallel:
      - service: light.turn_on
        data:
          transition: 10
          rgb_color:
            - 255
            - 0
            - 0
          brightness: 255
        target:
          entity_id:
            - light.office_desk_leds
mode: single
