#       __  __ _                     __  __ 
#  ___ / _|/ _(_)__ ___   ___   ___ / _|/ _|
# / _ \  _|  _| / _/ -_) |___| / _ \  _|  _|
# \___/_| |_| |_\__\___|       \___/_| |_|  
#                                           
#--FROM https://github.com/smcnab1/op-question-mark

alias: 'Lighting Office Off'
description: 'Automation to turn off all office lights.'
trigger: []
condition: []
action:
  - parallel:
      - if:
          - condition: state
            entity_id: light.office_desk_lamp
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.office_desk_lamp
      - if:
          - condition: state
            entity_id: light.office_leds
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.office_leds
mode: single
