#   __                        _           _ 
#  / _|__ _ _ _    __ ___ _ _| |_ _ _ ___| |
# |  _/ _` | ' \  / _/ _ \ ' \  _| '_/ _ \ |
# |_| \__,_|_||_| \__\___/_||_\__|_| \___/_|
#                                           
#--FROM https://github.com/smcnab1/op-question-mark

alias: HA System Fan Control
description: >-
  Controls server cabinet temperature using temperature sensor and USB fans in
  Sonoff USB plugs
trigger:
  - platform: numeric_state
    entity_id: sensor.server_temperature
    above: 30
    id: HOT
  - platform: numeric_state
    entity_id: sensor.server_temperature
    below: 30
    id: COOL
condition: []
action:
  - if:
      - condition: trigger
        id: HOT
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.server_fans
      - service: notify.mobile_app_ipad
        data:
          message: It's getting a little hot in there
          title: Server Fans On
    else: []
  - if:
      - condition: trigger
        id: COOL
    then:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.server_fans
      - service: notify.mobile_app_ipad
        data:
          title: Server Fans Off
          message: It's not so hot in there
mode: single

