#   __                        _           _ 
#  / _|__ _ _ _    __ ___ _ _| |_ _ _ ___| |
# |  _/ _` | ' \  / _/ _ \ ' \  _| '_/ _ \ |
# |_| \__,_|_||_| \__\___/_||_\__|_| \___/_|
#                                           
#--FROM https://github.com/smcnab1/op-question-mark

alias: HA System Fan Control
description: Controls server cabinet temperature using temperature sensor and USB fans in Sonoff USB plugs
trigger: []
condition: []
action:
  - if:
      - type: is_temperature
        condition: device
        device_id: 7ab72c275e4466f60c318693cc65c5dd
        entity_id: sensor.server_temperature
        domain: sensor
        above: 30
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.sonoff_100149c418_1
      - service: notify.mobile_app_sam_s_mac_mini
        data:
          message: It's getting a little hot in there
          title: Server Fans On
    else: []
  - wait_for_trigger:
      - type: temperature
        platform: device
        device_id: 7ab72c275e4466f60c318693cc65c5dd
        entity_id: sensor.server_temperature
        domain: sensor
        below: 30
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.sonoff_100149c418_1
  - service: notify.mobile_app_sam_s_mac_mini
    data:
      title: Server Fans Off
      message: It's not so hot in there
mode: single
