#             _ _                 _      _       
#  _ __  __ _(_) |  _  _ _ __  __| |__ _| |_ ___ 
# | '  \/ _` | | | | || | '_ \/ _` / _` |  _/ -_)
# |_|_|_\__,_|_|_|  \_,_| .__/\__,_\__,_|\__\___|
#                       |_|                      
#--FROM https://github.com/smcnab1/op-question-mark

alias: HA System Mail Update
description: Automation to send me updates on any packages en-route to the house
mode: single
trigger:
  - platform: state
    entity_id:
      - sensor.mail_packages_in_transit
condition:
  - condition: template
    value_template: >-
      "{{ ((as_timestamp(now()) -
      as_timestamp(states.sensor.mail_packages_in_transit.last_changed)) < 15
      and states('sensor.mail_packages_in_transit')|int > 0) }}"
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - parallel:
      - service: notify.mobile_app_iphone
        data:
          title: Mail & Packages Update
          message: "{{ states('sensor.mail_summary')}}"
          data:
            push:
              thread-id: homeassistant-mail
              sound:
                name: US-EN-Alexa-Mail-Has-Arrived.wav
                critical: 1
                volume: 0.3
      - if:
          - condition: state
            entity_id: binary_sensor.sam_s_mac_mini_active
            state: "on"
        then:
          - service: notify.mobile_app_sam_s_mac_mini
            data:
              title: Mail & Packages Update
              message: "{{ states('sensor.mail_summary')}}"
              data:
                push:
                  thread-id: homeassistant-mail
                  sound:
                    name: US-EN-Alexa-Mail-Has-Arrived.wav
                    critical: 1
                    volume: 0.3
