#     _        _      _                                                 _   _  __      
#  __| |_ _  _| |_ __| |_____ __ ___ _    _ __ _ _ ___   ___   _ _  ___| |_(_)/ _|_  _ 
# (_-< ' \ || |  _/ _` / _ \ V  V / ' \  | '_ \ '_/ -_) |___| | ' \/ _ \  _| |  _| || |
# /__/_||_\_,_|\__\__,_\___/\_/\_/|_||_| | .__/_| \___|       |_||_\___/\__|_|_|  \_, |
#                                        |_|                                      |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: HA System Shutdown Pre Notify
description: >-
  Automation which sends notification to my mac, wifes phone and google hubs
  through TTS to alert us that system is restartinh. Gives the wife a heads up
  that things won't work for a few minutes.
mode: single
trigger:
  - platform: homeassistant
    event: shutdown
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: person.leah
        state: home
      - condition: state
        entity_id: person.sam
        state: home
action:
  - parallel:
      - if:
          - condition: state
            entity_id: person.leah
            state: home
        then:
          - service: notify.mobile_app_leah_s_iphone
            data:
              message: Things won't work. So silly eh
              title: Home Assistant - Restarting
      - if:
          - condition: state
            entity_id: binary_sensor.sam_s_mac_mini_active
            state: "on"
        then:
          - service: notify.mobile_app_sam_s_mac_mini
            data:
              title: Home Assistant - System Management
              message: Home Assistant is Restarting
        else:
          - service: notify.mobile_app_iphone
            data:
              message: Home Assistant is Restarting
              title: Home Assistant - System Management
  - service: tts.cloud_say
    data:
      entity_id: media_player.bedroom_google_home
      message: >-
        Home Assistant is Restarting. Things may not work until it is back up.
        So silly, so silly
  - service: tts.cloud_say
    data:
      entity_id: media_player.living_room_google_home
      message: >-
        Home Assistant is Restarting. Things may not work until it is back up.
        So silly, so silly
  - if:
      - condition: state
        entity_id: person.sam
        state: not_home
    then:
      - service: notify.mobile_app_iphone
        data:
          title: HA - System Notification
          message: Home Assistant has Shutdown
