#  _        _    _     _        _                  _           
# | |_ __ _| |__| |___| |_   __| |_  __ _ _ _ __ _(_)_ _  __ _ 
# |  _/ _` | '_ \ / -_)  _| / _| ' \/ _` | '_/ _` | | ' \/ _` |
#  \__\__,_|_.__/_\___|\__| \__|_||_\__,_|_| \__, |_|_||_\__, |
#                                            |___/       |___/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: HA System Tablet Charging
description: Automation to trigger dashboard tablet's charging schedule. When battery level gets below 40%, charging begins. When above 90%, charging stops.
mode: single
trigger: []
condition: []
action:
  - if:
      - condition: numeric_state
        entity_id: sensor.dashboard_tablet_battery
        below: "40"
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.tablet_charger
    else:
      - wait_for_trigger:
          - platform: numeric_state
            entity_id: sensor.dashboard_tablet_battery
            above: "90"
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.tablet_charger
