#             _ _      _     _ _                    _ 
#  _ __  __ _(_) |  __| |___| (_)_ _____ _ _ ___ __| |
# | '  \/ _` | | | / _` / -_) | \ V / -_) '_/ -_) _` |
# |_|_|_\__,_|_|_| \__,_\___|_|_|\_/\___|_| \___\__,_|
#                                                     
#--FROM https://github.com/smcnab1/op-question-mark

alias: Notify Mail Delivered
description: Automation to send me updates on any packages delivered to the house
initial_state: true
trigger:
  #Trigger if mail or packages get updated
  - platform: state
    entity_id: sensor.mail_amazon_packages_delivered
  - platform: state
    entity_id: sensor.mail_evri_delivered
  - platform: state
    entity_id: sensor.mail_royal_mail_delivered
#send only if mail or packages are more than 0
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ ((as_timestamp(now()) - as_timestamp(states.sensor.mail_amazon_packages_delivered.last_changed)) < 15 and states('sensor.mail_amazon_packages_delivered')|int > 0) }}"
      - condition: template
        value_template: "{{ ((as_timestamp(now()) - as_timestamp(states.sensor.mail_evri_delivered.last_changed)) < 15 and states('sensor.mail_evri_delivered')|int > 0) }}"
      - condition: template
        value_template: "{{ ((as_timestamp(now()) - as_timestamp(states.sensor.mail_royal_mail_delivered.last_changed)) < 15 and states('sensor.mail_royal_mail_delivered')|int > 0) }}"
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - parallel:
      - service: notify.mobile_app_iphone
        data:
          title: Mail & Packages Update
          message: "{{ states('sensor.mail_summary_delivered')}}"
          data:
            push:
              thread-id: homeassistant-mail
              sound:
                name: US-EN-Alexa-Mail-Has-Arrived.wav
                critical: 1
                volume: 0.3
            actions:
              - action: OPEN
                title: Amazon
                uri: https://www.amazon.co.uk/gp/css/order-history
                icon: |
                  {%- if states("sensor.mail_amazon_packages_delivered")|int(0) > 1 -%}
                    sfsymbols:envelope.badge
                  {%- else -%}
                    sfsymbols:envelope
                  {%- endif -%}
              - action: OPEN
                title: Royal Mail
                uri: https://www.royalmail.com/track-your-item
                icon: >
                  {%- if states("sensor.mail_royal_mail_delivered")|int(0) > 1 -%}
                    sfsymbols:envelope.badge
                  {%- else -%}
                    sfsymbols:envelope
                  {%- endif -%}
              - action: OPEN
                title: Evri
                uri: https://www.evri.com/track-a-parcel
                icon: |
                  {%- if states("sensor.mail_evri_delivered")|int(0) > 1 -%}
                    sfsymbols:envelope.badge
                  {%- else -%}
                    sfsymbols:envelope
                  {%- endif -%}
              - action: OPEN
                title: Mail App
                uri: message:Mail+and+Parcels
                icon: >
                  {%- if states("sensor.mail_amazon_packages_delivered")|int(0) > 1 -%}
                    sfsymbols:envelope.badge
                  {%- elif states("sensor.mail_evri_delivered")|int(0) > 1 -%}
                    sfsymbols:envelope.badge
                  {%- elif states("sensor.mail_royal_mail_delivered")|int(0) > 1 -%}
                    sfsymbols:envelope.badge
                  {%- else -%}
                    sfsymbols:envelope
                  {%- endif -%}
      - if:
          - condition: state
            entity_id: binary_sensor.mac_mini_active
            state: "on"
        then:
          - service: notify.mobile_app_ipad
            data:
              title: Mail & Packages Update
              message: "{{ states('sensor.mail_summary_delivered')}}"
              data:
                push:
                  thread-id: homeassistant-mail
                  sound:
                    name: US-EN-Alexa-Mail-Has-Arrived.wav
                    critical: 1
                    volume: 0.3
                actions:
                  - action: OPEN
                    title: Amazon
                    uri: https://www.amazon.co.uk/gp/css/order-history
                    icon: >
                      {%- if states("sensor.mail_amazon_packages_delivered")|int(0) > 1 -%}
                        sfsymbols:envelope.badge
                      {%- else -%}
                        sfsymbols:envelope
                      {%- endif -%}
                  - action: OPEN
                    title: Royal Mail
                    uri: https://www.royalmail.com/track-your-item
                    icon: >
                      {%- if states("sensor.mail_royal_mail_delivered")|int(0) > 1 -%}
                        sfsymbols:envelope.badge
                      {%- else -%}
                        sfsymbols:envelope
                      {%- endif -%}
                  - action: OPEN
                    title: Evri
                    uri: https://www.evri.com/track-a-parcel
                    icon: >
                      {%- if states("sensor.mail_evri_delivered")|int(0) > 1 -%}
                        sfsymbols:envelope.badge
                      {%- else -%}
                        sfsymbols:envelope
                      {%- endif -%}
                  - action: OPEN
                    title: Mail App
                    uri: message:Mail+and+Parcels
                    icon: >
                      {%- if states("sensor.mail_amazon_packages_delivered")|int(0) > 1 -%}
                        sfsymbols:envelope.badge
                      {%- elif states("sensor.mail_evri_delivered")|int(0) > 1 -%}
                        sfsymbols:envelope.badge
                      {%- elif states("sensor.mail_royal_mail_delivered")|int(0) > 1 -%}
                        sfsymbols:envelope.badge
                      {%- else -%}
                        sfsymbols:envelope
                      {%- endif -%}