#  _                                _                           _   _  __      
# | |_ ___ _ __  _ __  ___ _ _ __ _| |_ _  _ _ _ ___   _ _  ___| |_(_)/ _|_  _ 
# |  _/ -_) '  \| '_ \/ -_) '_/ _` |  _| || | '_/ -_) | ' \/ _ \  _| |  _| || |
#  \__\___|_|_|_| .__/\___|_| \__,_|\__|\_,_|_| \___| |_||_\___/\__|_|_|  \_, |
#               |_|                                                       |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: Notify Temp Report
description: Automation which sends overview of temperature across house.
mode: single
trigger: []
condition: []
action:
  - service: notify.mobile_app_sams_iphone
    data:
      title: Temperature Report
      message: >
        Bedroom: {{ states('sensor.bedroom_temperature') }}°C | Living room: {{
        states('sensor.living_room_temperature') }}°C | Hall: {{
        states('sensor.living_room_temperature') }}°C | Bathroom: {{
        states('sensor.bathroom_temperature') }}°C | Kitchen: {{
        states('sensor.kitchen_temperature') }}°C | Office: {{
        states('sensor.living_room_temperature') }}°C | Outside: {{
        state_attr('weather.weather', 'temperature') }}°C and it's {{
        states('weather.weather') }}
