#         _                  _             _  __    ___ 
# __ __ _| |_  ___ _ _ ___  (_)___ __ __ _(_)/ _|__|__ \
# \ V  V / ' \/ -_) '_/ -_) | (_-< \ V  V / |  _/ -_)/_/
#  \_/\_/|_||_\___|_| \___| |_/__/  \_/\_/|_|_| \___(_) 
#                                                       
#--FROM https://github.com/smcnab1/op-question-mark

alias: Notify Where is Leah
mode: single
trigger: []
condition: []
action:
  - service: notify.mobile_app_iphone
    data:
      title: Where is Leah?
      message: Leah is {{ states('sensor.leah_to_sam') }} mins away.
      data:
        action_data:
          latitude: "{{ state_attr('person.leah', 'latitude') }}"
          longitude: "{{ state_attr('person.leah', 'longitude') }}"
          second_latitude: "{{ state_attr('person.sam', 'latitude') }}"
          second_longitude: "{{ state_attr('person.sam', 'longitude') }}"
