#                 _                         
#  _ __  __ _ _ _| |_ _  _   ___   ___ _ _  
# | '_ \/ _` | '_|  _| || | |___| / _ \ ' \ 
# | .__/\__,_|_|  \__|\_, |       \___/_||_|
# |_|                 |__/                  
#--FROM https://github.com/smcnab1/op-question-mark

alias: Lighting Party On
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.party
    from: 'off'
    to: 'on'
action:
  service: script.party_on
