id: '1659611701361'
alias: Citymapper Notifications - Sam
description: ''
trigger: []
condition:
- condition: state
  entity_id: person.sam_mcnab
  state: home
action:
- service: notify.mobile_app_sam_s_phone
  data:
    data:
      actions:
      - action: URI
        title: Open Citymapper
        uri: https://citymapper.com/directions?startcoord=51.5477409362793%2C-0.18949000537395477&startname=Home&startaddress=Clockwork%20Factory%20Apartments%2C%20London%2C%20NW6%201RZ
    message: Want help getting somewhere?
mode: single
