esphome:
  name: "esp-bed-sensor"

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "NMZztEaFnj6Ia0XFZzstFPDW5Qdq1MqenPevnSLMpIY="

ota:
  password: "NMZztEaFnj6Ia0XFZzstFPDW5Qdq1MqenPevnSLMpIY="


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.115
    gateway: 192.168.1.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-F849Ac"
    password: "5jk1QYzLXM0y"

captive_portal:
    
binary_sensor:
  - platform: gpio
    pin:
      number: 23
      inverted: true
      mode:
        input: true
        pullup: true
    name: Bed Sensor Leah
    filters:
      - delayed_off: 20s
    
  - platform: gpio
    pin:
      number: 21
      inverted: true
      mode:
        input: true
        pullup: true
    name: Bed Sensor Sam
    filters:
      - delayed_off: 20s