esphome:
  name: "new-bed-sensor"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-F849Ac"
    password: "FIAIludw048m"

captive_portal:
    
    
binary_sensor:
  - platform: gpio
    pin:
      number: 23
      inverted: true
      mode:
        input: true
        pullup: true
    name: Leah
    filters:
      - delayed_off: 20s
  - platform: gpio
    pin:
      number: 19
      inverted: true
      mode:
        input: true
        pullup: true
    name: Sam
    filters:
      - delayed_off: 20s