#  _                                                                  _   _          
# | |_ _  _ _ _ _ _ _  _   _  _ _ __   ___ __ _ _ __    ___   __ _ __| |_(_)___ _ _  
# | ' \ || | '_| '_| || | | || | '_ \ (_-</ _` | '  \  |___| / _` / _|  _| / _ \ ' \ 
# |_||_\_,_|_| |_|  \_, |  \_,_| .__/ /__/\__,_|_|_|_|       \__,_\__|\__|_\___/_||_|
#                   |__/       |_|                                                   
#--FROM https://github.com/smcnab1/op-question-mark

alias: Hurry Up Sam Action
description: Automation which is triggered by the wife through actionable notification. Flashes lights in office red and plays TTS through google home telling me to hurry up. Also sends me a notification on PC on other monitor.
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: HURRY
condition:
  - condition: state
    entity_id: binary_sensor.sam_7he_ex7reme
    state: 'on'
action:
  - service: scene.create
    data:
      scene_id: prehurryup
      snapshot_entities: light.office_desk_led
  - service: media_player.volume_set
    data:
      volume_level: 0.8
    target:
      entity_id: media_player.living_room_speaker
  - service: tts.cloud_say
    data:
      entity_id: media_player.living_room_speaker
      message: Hurry Up and get off your xbox! I want some attention
  - repeat:
      count: '30'
      sequence:
      - service: light.turn_on
        data:
          color_name: red
          brightness: 255
        target:
          entity_id: light.office_desk_led
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 250
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.office_desk_led
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 250
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.prehurryup
  - service: media_player.volume_set
    data:
      volume_level: 0.4
    target:
      entity_id: media_player.living_room_speaker
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - if:
    - condition: state
      entity_id: binary_sensor.sam_7he_ex7reme
      state: 'on'
    then:
    - service: media_player.volume_set
      data:
        volume_level: 1
      target:
        entity_id: media_player.living_room_speaker
    - service: tts.cloud_say
      data:
        entity_id: media_player.living_room_speaker
        message: Hurry Up and get off your xbox! I want some attention
    - repeat:
        count: '30'
        sequence:
        - service: light.turn_on
          data:
            color_name: red
            brightness: 255
          target:
            entity_id: light.office_desk_led
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 250
        - service: light.turn_off
          data: {}
          target:
            entity_id: light.office_desk_led
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 250
    else: []
  - service: notify.mobile_app_leah_s_iphone
    data:
      message: clear_notification
      data:
        tag: hurryup
mode: single
