#  _                                                                   _   _  __      
# | |_ _  _ _ _ _ _ _  _   _  _ _ __   ___ __ _ _ __    ___   _ _  ___| |_(_)/ _|_  _ 
# | ' \ || | '_| '_| || | | || | '_ \ (_-</ _` | '  \  |___| | ' \/ _ \  _| |  _| || |
# |_||_\_,_|_| |_|  \_, |  \_,_| .__/ /__/\__,_|_|_|_|       |_||_\___/\__|_|_|  \_, |
#                   |__/       |_|                                               |__/ 
#--FROM https://github.com/smcnab1/op-question-mark

alias: Media Hurry Up Sam Notify
description: >-
  Automation which sends notification to wifes phone when I turn on my XBOX and
  she is home. Uses actionable notifications to trigger a hurry up automation.
trigger:
  - platform: state
    entity_id:
      - binary_sensor.xbox_status
    to: "on"
condition:
  - condition: state
    entity_id: person.leah
    state: home
action:
  - service: notify.mobile_app_leah_iphone
    data:
      title: Sam's on his XBOX
      message: What would you like to do?
      data:
        icon: null
        ttl: 0
        visibility: public
        tag: hurryup
        push:
          sound:
            volume: 1
        actions:
          - action: HURRY
            title: Hurry Up
            icon: sfsymbols:person.fill.checkmark
            destructive: true
          - action: IGNORE
            title: Nothing
            icon: sfsymbols:person.fill.xmark
  - wait_for_trigger:
      - platform: state
        entity_id:
          - binary_sensor.xbox_status
        to: "off"
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: IGNORE
    continue_on_timeout: false
  - service: notify.mobile_app_leah_iphone
    data:
      message: clear_notification
      data:
        tag: hurryup
mode: single
