#          _                            _                 _   
# __ _____| |_  _ _ __  ___   __ _ _  _| |_ ___   ___ ___| |_ 
# \ V / _ \ | || | '  \/ -_) / _` | || |  _/ _ \ (_-</ -_)  _|
#  \_/\___/_|\_,_|_|_|_\___| \__,_|\_,_|\__\___/ /__/\___|\__|
#                                                             
#--FROM https://github.com/smcnab1/op-question-mark

alias: Media Volume Auto Set
description: Automation that auto-sets volume of Google Home devices requested by wife.
mode: single
trigger:
  - platform: time
    at: "10:00:00"
    id: TURNUP
  - platform: time
    at: "22:00:00"
    id: TURNDOWN
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: person.sam
        state: home
      - condition: state
        entity_id: person.leah
        state: home
action:
  - choose:
      - conditions:
          - condition: trigger
            id: TURNDOWN
        sequence:
          - service: media_player.volume_set
            data:
              volume_level: 0.38
            target:
              entity_id:
                - media_player.bedroom_google_home
                - media_player.living_room_google_home
      - conditions:
          - condition: trigger
            id: TURNUP
        sequence:
          - service: media_player.volume_set
            data:
              volume_level: 0.65
            target:
              entity_id:
                - media_player.bedroom_google_home
                - media_player.living_room_google_home
